addons:
  apt:
    packages:
    - oracle-java8-installer
after_failure:
- cat target/log/*
- cat target/failsafe-reports/org.apache.syncope.fit.*-output.txt
before_install:
- echo 'MAVEN_OPTS="-Xms512m -Xmx1024m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"'
  >~/.mavenrc
before_script:
- cd fit/core-reference
cache:
  directories:
  - $HOME/.m2
install: travis_wait mvn --show-version --quiet -T 1C -P all,skipTests
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn --show-version verify -Dinvoker.streamLogs=true
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
